"""empty message

Revision ID: c8aa12630326
Revises: 
Create Date: 2020-09-23 17:20:02.613950

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.types import Text
# revision identifiers, used by Alembic.
revision = 'c8aa12630326'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('armor_bouns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('armorBouns', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attack_bouns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attackBouns', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('expansion', sa.String(), nullable=False),
    sa.Column('age', sa.String(), nullable=False),
    sa.Column('created_in', sa.String(), nullable=False),
    sa.Column('cost', postgresql.JSON(astext_type=Text()), nullable=False),
    sa.Column('build_time', sa.Integer(), nullable=False),
    sa.Column('reload_time', sa.Numeric(), nullable=False),
    sa.Column('attack_delay', sa.Numeric(), nullable=True),
    sa.Column('movement_rate', sa.Numeric(), nullable=False),
    sa.Column('line_of_sight', sa.Integer(), nullable=False),
    sa.Column('hit_points', sa.Integer(), nullable=False),
    sa.Column('unit_range', sa.String(), nullable=True),
    sa.Column('attack', sa.Integer(), nullable=False),
    sa.Column('armor', sa.String(), nullable=False),
    sa.Column('search_radius', sa.Integer(), nullable=True),
    sa.Column('accuracy', sa.String(), nullable=True),
    sa.Column('blast_radius', sa.Numeric(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unit_armor_bouns',
    sa.Column('armor_bouns_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['armor_bouns_id'], ['armor_bouns.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.id'], ),
    sa.PrimaryKeyConstraint('armor_bouns_id', 'unit_id')
    )
    op.create_table('unit_attack_bouns',
    sa.Column('attack_bouns_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['attack_bouns_id'], ['attack_bouns.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.id'], ),
    sa.PrimaryKeyConstraint('attack_bouns_id', 'unit_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('unit_attack_bouns')
    op.drop_table('unit_armor_bouns')
    op.drop_table('unit')
    op.drop_table('attack_bouns')
    op.drop_table('armor_bouns')
    # ### end Alembic commands ###
