"""empty message

Revision ID: bfc1db22645c
Revises: c5dc5a88c405
Create Date: 2020-10-05 02:11:00.039322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfc1db22645c'
down_revision = 'c5dc5a88c405'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('unit_data', 'armor',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('unit_data', 'hit_points',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('unit_data', 'line_of_sight',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('unit_data', 'line_of_sight',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('unit_data', 'hit_points',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('unit_data', 'armor',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
