"""empty message

Revision ID: c5dc5a88c405
Revises: 
Create Date: 2020-10-04 23:23:05.390118

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c5dc5a88c405'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unit_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('expansion', sa.String(), nullable=False),
    sa.Column('age', sa.String(), nullable=False),
    sa.Column('created_in', sa.String(), nullable=False),
    sa.Column('cost', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('build_time', sa.Integer(), nullable=True),
    sa.Column('reload_time', sa.Float(), nullable=True),
    sa.Column('attack_delay', sa.Float(), nullable=True),
    sa.Column('movement_rate', sa.Float(), nullable=True),
    sa.Column('line_of_sight', sa.Integer(), nullable=True),
    sa.Column('hit_points', sa.Integer(), nullable=True),
    sa.Column('range', sa.String(), nullable=True),
    sa.Column('attack', sa.Integer(), nullable=True),
    sa.Column('armor', sa.String(), nullable=True),
    sa.Column('attack_bonus', sa.String(), nullable=True),
    sa.Column('armor_bonus', sa.String(), nullable=True),
    sa.Column('search_radius', sa.Integer(), nullable=True),
    sa.Column('accuracy', sa.String(), nullable=True),
    sa.Column('blast_radius', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('unit_data')
    # ### end Alembic commands ###
